### ISSUE TITLE
Once it disconnects, how do you get it back online and responding?

### ISSUE THREAD

**Issue by PapyrusTheGrrreat** [sunset-developer/ComediBot#1]

**Comment by sunset-developer** [comment]
Can you be more specific?

**Comment by PapyrusTheGrrreat** [comment]
Sometimes it just goes offline for an hour or so. Is there a way to prevent this?
Also the bot doesn't seem to exist anymore at all.

**Comment by sunset-developer** [comment]
I currently have taken down the bot until I further develop it. It gained popularity and was becoming a bit pricey to maintain. Gonna create something better and have it back up soon :)
